no.nav.security.jwt:
  client:
    registration:
      eux-credentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${AZURE_APP_EUX_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

METRICS_REQUESTFILTER_ENABLE: false

kafka:
  topic: ${KAFKA_STATISTIKK_TOPICNAME}
  keystore.path: ${KAFKA_KEYSTORE_PATH:}
  truststore.path: ${KAFKA_TRUSTSTORE_PATH:}
  credstore.password: ${KAFKA_CREDSTORE_PASSWORD:}
  brokers: ${KAFKA_BROKERS:localhost:9092}
  security.protocol: SSL
  statistikk-inn:
    topic: ${KAFKA_STATISTIKK_TOPICNAME_INN}
    groupid: eessi-pensjon-statistikk-group

  statistikk-ut:
    topic: ${KAFKA_STATISTIKK_TOPICNAME_UT}
    groupid: eessi-pensjon-statistikk-group

  statistikk-sed-sendt:
    topic: ${KAFKA_SEDSENDT_TOPIC}
    groupid: eessi-pensjon-statistikk-group

  statistikk-sed-mottatt:
    topic: ${KAFKA_SEDMOTTATT_TOPIC}
    groupid: eessi-pensjon-statistikk-group

#Metrics
management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info, health, metrics, prometheus
    export:
      prometheus:
        enabled: true
    prometheus:
      enabled: true
