kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: eessi-pensjon-statistikk-q2
  namespace: eessipensjon
  labels:
    team: eessipensjon
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: test
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: KAFKA_STATISTIKK_TOPICNAME_INN
      value: privat-eessipensjon-statistikk-q2
    - name: KAFKA_STATISTIKK_TOPICNAME_UT
      value: eessipensjon-statistikk-q2
    - name: KAFKA_SEDSENDT_TOPIC
      value: eessi-basis-sedSendt-v1-q2
    - name: KAFKA_SEDMOTTATT_TOPIC
      value: eessi-basis-sedMottatt-v1-q2
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
    - name: EUX_RINA_API_V1_URL
      value: https://eux-rina-api-q2.nais.preprod.local/cpi
    - name: S3_FSS_URL
      value: http://objectstore.rook-ceph.svc.nais.local
    - name: EESSI_PENSJON_STATISTIKK_S3_CREDS_USERNAME
      value: 6CM9IETIVLHPA21OCIWT
    - name: ENV
      value: q2
    - name: PENSJONSINFORMASJON_URL
      value: https://pensjon-pen-q2.nais.preprod.local/pen/api/pensjonsinformasjon/v1
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: https://app-q1.adeo.no/tpsws-aura/ws/Person/v3
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql

  image: {{ image }}
  ingresses:
    - https://eessi-pensjon-statistikk-q2.nais.preprod.local
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi
#  vault:
#    enabled: true
#    paths:
#      - kvPath: {{serviceuserkv}}
#        mountPath: /var/run/secrets/nais.io/srveessipensjonstats
#      - kvPath: {{appsecrets}}
#        mountPath: /var/run/secrets/nais.io/appcredentials
