name: Deploy topics

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v2

      # DEPLOYER TIL NAIS
      - name: 'Deploy to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/topics/topic-privat-statistikk-q2.yaml