name: Deploy topics

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'src/**'
jobs:
  deploy_topics:
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v3

      - name: 'Deploy privat-statistikk-q2 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-privat-statistikk-q2.yaml

      - name: 'Deploy privat-statistikk-q1 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-privat-statistikk-q1.yaml


      - name: 'Deploy privat-statistikk to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/topic-privat-statistikk.yaml

      - name: 'Deploy public-statistikk-q2 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-public-statistikk-q2.yaml

      - name: 'Deploy public-statistikk-q1 to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/topics/topic-public-statistikk-q1.yaml

      - name: 'Deploy public-statistikk to eessipensjon namespace'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/topic-public-statistikk.yaml